baseURL = "https://booiris.space"
languageCode = "en-us"
theme = "yinyang"
DefaultContentLanguage = "cn"
canonifyURLs = false

[languages]

# [languages.en]
#   contentDir = "content/en"
#   languageName = "English"
#   weight = 1
[languages.cn]
contentDir = "content"
languageName = "cn"
weight = 2

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
style = "github"
tabWidth = 2

[author]
name = "Booiris"
homepage = "https://booiris.space"

[params]
headTitle = "HELLO WORLD"
mainSections = ["posts"]
favicon = "/avatar.svg"
lazyImage = true
description = "Live long and prosper."

[[params.socials]]
name = "About"
link = "/about"

[[params.socials]]
name = "Github"
link = "https://github.com/booiris"
blank = true

[[params.socials]]
name = "Memos"
link = "/memos"
# [[params.socials]]
# name = "Game"
# link = ""
# [[params.socials]]
# name = "Picture"
# link = ""
